export const APP_CONSTANTS = {
  appName: "RECRUIT",
  candidates: "Candidates",
  candidateInformation: "Candidate Information",
  searchCandidate: "Search candidate",
  filters: "Filters",
  export: "Export",
  addCandidate: "Add Candidate",
  adverseActions: "Adverse Actions",
  engage: "Engage",
  engaged: "Engaged",
  clear: "Clear",
  consider: "Consider",
  status: "Status",
  adjudication: "Adjudication",
  location: "Location",
  date: "Date",
  name: "Name",
  candidateNotFound: "Candidate not found",
  backToCandidates: "Back to Candidates",
  noCandidatesFound: "No candidates found.",
  noCourtSearches: "No court searches recorded for this candidate.",
  reportInformation: "Report Information",
  preAdverseAction: "Pre-Adverse Action",
  home: "Home",
  logs: "Logs",
  analytics: "Analytics",
  account: "Account",
  screenings: "Screenings",
  searchLabel: "SEARCH",
  statusLabel: "STATUS",
} as const;
