spring.application.name=spring-logger-practice
server.port=8082


logging.level.com.example.logger=DEBUG


logging.file.name=logs/spring-logger-practice.log


logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
